### PR TITLE
feat(pro): added pro functionality to travis

### PR DESCRIPTION
**Pull request by vladshub**
This allows connecting to travis-ci.com and working against it.
This should also be a solution for #4

### CODE REVIEW

**Comment by briandela** [comment]
@felixrieseberg Would love to help with anything necessary to get this PR in and published. The vs code extension is great but unfortunately doesn't work with paid travis accounts right now.

**Comment by felixrieseberg** [comment]
Sorry, I just forgot to handle this - it's an amazing PR, thank you so much 🙌

**Comment by felixrieseberg** [comment]
And published!

**Comment by briandela** [comment]
@felixrieseberg thanks for taking it. However, now that it's published and I've updated to the latest published version, I don't see the travis option at all in the status bar.

**Comment by briandela** [comment]
@felixrieseberg Looks like this is the error:

``` console
shell.ts:422 Travis.new is not a function: TypeError: Travis.new is not a function
    at TravisStatusIndicator.getTeravis (/Users/brian/.vscode/extensions/felixrieseberg.vsc-travis-ci-status-1.0.0/out/travis-status.js:188:38)
    at /Users/brian/.vscode/extensions/felixrieseberg.vsc-travis-ci-status-1.0.0/out/travis-status.js:33:27
    at /Users/brian/.vscode/extensions/felixrieseberg.vsc-travis-ci-status-1.0.0/node_modules/git-rev-2/index.js:9:5
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by vladshub** [comment]
Thanks @felixrieseberg and sorry for the mess it was the first time that I wrote something in this...

**Comment by felixrieseberg** [comment]
No worries, all contributions are amazing.

**Pull request merged**
